### ISSUE TITLE
在模拟器你的应用已经安装成功，但是屏幕上没有LOGO!

### ISSUE THREAD

**Issue by anlexN** [fkzhang/WechatUnrecalled#117]
在模拟器你的应用已经安装成功，xposed框架也安装成功。但是屏幕上没有你的应用LOGO! 被隐藏了吗？我使用的是逍遥模拟器android version: 4.2.2 .

**Comment by vipzrx** [comment]
微信的设置中，有设置入口

**Comment by anlexN** [comment]
@vipzrx 如何设置，我找不到你说的

**Comment by xiiaokhong98** [comment]
打开Xposed--模块--按微信转发模块--然后按上角显示 最后重启

**Comment by anlexN** [comment]
nice to you!
