### ISSUE TITLE
自动回复

### ISSUE THREAD

**Issue by Subways-Sun** [fkzhang/WechatUnrecalled#139]
自动回复打开的状态下，如果从其他设备恢复聊天记录，自动回复机器人会针对每条新增加的聊天记录进行回复，望修正

**Comment by vipzrx** [comment]
提交下xposed的log

**Comment by vipzrx** [comment]
你描述的这个不正常吗？ 有了新的消息，针对新的消息回复？

**Comment by fkzhang** [comment]
这个 很难区分 建议恢复时关闭自动回复
