### ISSUE TITLE
今天起床微信闪退了

### ISSUE THREAD

**Issue by qq550477708** [fkzhang/WechatUnrecalled#166]
关模块后正常了

**Comment by lnxctz** [comment]
我的也是，但另一个手机就暂时没问题

**Comment by hyhyhykw** [comment]
我以为是我手机的问题

**Comment by Travisss** [comment]
我的也是，不懂为什么

**Comment by halflover** [comment]
我也是，以为系统出问题了，重启手机几次都那样，重置微信也不行，卸载安装低版本微信也不行。后来安装1.2的weexpose就正常了。。。

（用分身大师的微信分身登录正常，不受影响，只是官方版本会点了闪退或提示微信崩溃）

**Comment by Travisss** [comment]
@halflover 页面上我只找到了1.1版本的

**Comment by halflover** [comment]
1.2是一个独立的版本。1.2_4.16

**Comment by yuehun** [comment]
一样 闪退

**Comment by bmqy** [comment]
哦哦，metoo

**Comment by slb116763814** [comment]
我也同样闪退，框架里面去掉模块重启就可以正常使用微信。我想知道，如何在不清除聊天记录的同时可以清理干净微信所有缓存以及微X模块缓存，（我理解的是可能哪里有冲突）然后再给微X模块打上勾，试试看行不行。

**Comment by Travisss** [comment]
确实1.2的就可以用了

**Comment by yuehun** [comment]
都更新1.8好了 还用什么1.2

**Comment by sgfeeling** [comment]
我的装了1.8也不行，模块列表下找不到这个模块，微信里面也没有，等于是没装上

**Comment by sgfeeling** [comment]
我的装了1.8也不行，模块列表下找不到这个模块，微信里面也没有，等于是没装上
