### ISSUE TITLE
详情页面内总会显示［已删除］

### ISSUE THREAD

**Issue by the-eric-kwok** [fkzhang/WechatUnrecalled#18]
如题，图片无法粘贴上来，手机是酷派大神F1电信版，系统MIUI6.3.17，安卓4.4.4

**Comment by fkzhang** [comment]
哪个版本的模块和微信？

**Comment by shiw019** [comment]
你好fkzhang，有项目合作需求，麻烦加我微信shiw019

**Comment by erickwoc** [comment]
抱歉……我已经删掉xp了……所以不能确定

2016年4月7日星期四，fkzhang <notifications@github.com> 写道：
