### ISSUE TITLE
魅族note4  之前可以用 后来更新最新的都不显示

### ISSUE THREAD

**Issue by shawgood** [fkzhang/WechatUnrecalled#212]
各种办法都试过了  有没有和我一样的 ，微信版本从6.5.8到6.5.10都试过了（微信版本都是从大神的百度云盘下载的）  wx也是试了最新的版本了 但是微信里面就是不显示wx插件 不知道是什么原因   其他的插件又可以用

**Comment by fkzhang** [comment]
发日志

2017-08-22 6:56 GMT+02:00 shawgood <notifications@github.com>:

**Comment by shawgood** [comment]
英文不太好 有点看不明白 尴尬了

**Comment by shawgood** [comment]
我都格机了  然后试了还几遍  没日志了 尴尬了

**Comment by shawgood** [comment]
@fkzhang 我都格机了 然后试了还几遍 没日志了 尴尬了

**Comment by shawgood** [comment]
@fkzhang wxcleaner2这个软件用了还是没效果，手动那个文件  我也找了 找不到 没有
