### ISSUE TITLE
@所有人 功能无效？

### ISSUE THREAD

**Issue by halflover** [fkzhang/WechatUnrecalled#221]
昨天用@所有人，原来有个隐藏选择现在没有了，选择人员后蹦出一个输入内容（不知是什么项目）随便输入，确定后返回。再输入内容发送。其他人没有被@提醒。

**Comment by halflover** [comment]
@多个成员

**Comment by halflover** [comment]
原来与微信版本号有关。微信6.5.8以前版本@多个成员，失效了。

**Comment by fkzhang** [comment]
无关 被tx和谐了
