### ISSUE TITLE
【建议】能否把微X助手的入口从微信的设置菜单里挪走？

### ISSUE THREAD

**Issue by cedric1120** [fkzhang/WechatUnrecalled#246]
把微X助手的入口放在微信里，还是会有很大可能被想查我微信的人发现有这么一个插件，因为很醒目（一般的微信设置里没有这个菜单），点进去一看，不就知道这个助手能实现什么功能了？
能否把入口改为像另外一个应用一样的入口，单独放到应用列表里，而不放在微信里。放到应用列表里更容易隐藏。查我微信的人再怎么翻我微信，也不会发现有什么异样。

**Comment by cedric1120** [comment]
已经找到怎么设置了

**Comment by cooper1x** [comment]
@cedric1120 怎么隐藏？而且我还想隐藏微信好友右上角的菜单，还有长按转发和伪集赞的按钮等，就像没有装这个一样，但实际还是生效的。
