### ISSUE TITLE
伪集赞功能没有反应

### ISSUE THREAD

**Issue by phoenixlhs** [fkzhang/WechatUnrecalled#252]
模块版本：1.14_7_24
框架版本：v86
微信版本：6.5.13
手机型号：Le Pro3(骁龙821)
手机系统：EUI 5.8.18S(Android 6.0)
现象：长按朋友圈消息后，会弹出菜单，里面有伪集赞和伪评论，但是无论点哪个，都没有反应，连黑屏都没有。微X模块更新过好几个版本了……哪个版本都用不了……以前不知道这个Github地址，所以没地方反映这个问题

**Comment by fkzhang** [comment]
模块里有邮箱地址
试试我网盘里的微信版本 模块关于里

2017年11月7日 上午9:57，"phoenixlhs" <notifications@github.com>写道：

**Comment by phoenixlhs** [comment]
报告，还是不好使😔，点了什么反应都没有……我是不是应该重装微信了……

**Comment by fkzhang** [comment]
日志发来看看

**Comment by phoenixlhs** [comment]
您好，是在框架里看日志么？我看了一下，点“伪集赞”或者“伪评论”之后，并没有产生日志……原来的日志提示大小到上限了，我是清空日志之后观察的……

**Comment by fkzhang** [comment]
发来看看

2017-11-08 14:55 GMT+01:00 phoenixlhs <notifications@github.com>:

**Comment by phoenixlhs** [comment]
[error.log](https://github.com/fkzhang/WechatUnrecalled/files/1454214/error.log)

**Comment by phoenixlhs** [comment]
@fkzhang 大神，一个礼拜过去了……有什么消息么？

**Comment by luofengBJ** [comment]
遇到同样的问题~也是伪集赞出现问题。

**Comment by fkzhang** [comment]
用我百度云里的微信版本

**Comment by luofengBJ** [comment]
@fkzhang 应该是用了play版本~13的

**Comment by phoenixlhs** [comment]
用了微信的版本就好了……估计是之前装的play版
