### ISSUE TITLE
一加3上7.11的ROM用微X模块出现的BUG

### ISSUE THREAD

**Issue by RockZhou8** [fkzhang/WechatUnrecalled#296]
型号：一加3 A3000
ROM：7.11的 氧OS
微X模块：最新版的1.16-7.26
出现的bug：1.手机里某个app会突然的没有网络连接，无论切换飞行开关还是切换WIFI或4G流量都无法使之重新网络连接上，重启手机可解除bug，影响过的app：浏览器、夸克浏览器、QQ、TIM、微信、阴阳师、滴滴出行、SSR、谷歌市场、京东、哔哩哔哩等。该症状特别奇特，完全的随机性，且某个app无网络连接时，其他app均一切正常，丝毫没有断开网络连接的情况。
2.手机的设置-流量使用情况-应用联网控制，app的列表会加载失败，无法正常对app进行流量或WIFI的联网控制。该情况有一加论坛的氢OS 7.11的兄弟也碰到过。
![image](https://user-images.githubusercontent.com/17639060/34488700-704047ba-f014-11e7-926b-fbd253df1c21.png)

在使用Android 6.0版本ROM时从未出现过上述bug，看到有支持Android 7.11的XPOSED之后，同时也看到wexposed支持nougat了，才升级7.11的ROM，所以一开始认为是ROM问题。但经过对每个xposed里装的插件逐个开关排查时，发现启用了wexposed之后，便会出现这个问题，开启其他插件均无此问题。

**Comment by fkzhang** [comment]
无解
第一 没有一加手机 无法测试
第二 微x模块只在微信里挂钩不应该对其他软件有影响
第三 没有在网络有关的地方挂钩不应该有影响
第四 其他手机上没有出现你说的问题

**Comment by RockZhou8** [comment]
感谢解答,待我以后再刷新版ROM后继续测试.

**Comment by RockZhou8** [comment]
估计是无望了,论坛里一加3/一加3T/一加5 都出现过此问题,都是7.1的ROM
