### ISSUE TITLE
"已停止访问该网页"，是否可以绕过？

### ISSUE THREAD

**Issue by gMan1990** [fkzhang/WechatUnrecalled#314]
rt

**Comment by fkzhang** [comment]
哪里出现？

Op vr 4 mei 2018 20:09 schreef gMan1990 <notifications@github.com>:

**Comment by gMan1990** [comment]
www.tv115.com
你把这条消息发给你自己，然后点击链接

**Comment by fkzhang** [comment]
做不到

Op za 5 mei 2018 06:26 schreef gMan1990 <notifications@github.com>:

**Comment by vipzrx** [comment]
@gMan1990 https://www.zhihu.com/question/39295419
