### ISSUE TITLE
6.3.16无法使用

### ISSUE THREAD

**Issue by cxgreat2014** [fkzhang/WechatUnrecalled#34]
05-08 20:19:35.890 I/Xposed  (11036): WechatUnrecalled: wechat version 6.3.16.49_r03ae324 not supported!
05-08 20:19:46.520 I/Xposed  (11416): WechatForwarder Loaded app: com.tencent.mm 6.3.16.49_r03ae324
05-08 20:19:46.520 I/Xposed  (11416): WechatUnrecalled: wechat version 6.3.16.49_r03ae324 not supported!
05-08 20:23:07.393 I/Xposed  (12649): Loaded app: com.tencent.mobileqq
05-08 20:23:38.363 I/Xposed  (13285): Loaded app: com.tencent.mobileqq
05-08 20:24:09.447 I/Xposed  (14117): Loaded app: com.tencent.mobileqq
05-08 20:29:31.610 I/Xposed  (15658): WechatForwarder Loaded app: com.tencent.mm 6.3.16.49_r03ae324
05-08 20:29:31.621 I/Xposed  (15658): WechatUnrecalled: wechat version 6.3.16.49_r03ae324 not supported!
05-08 20:33:06.898 I/Xposed  (16474): Loaded app: com.tencent.mobileqq
05-08 20:43:48.246 I/Xposed  (18031): Loaded app: com.tencent.mobileqq
05-08 20:56:08.016 I/Xposed  (19191): Loaded app: com.tencent.mobileqq
05-08 21:04:50.966 I/Xposed  (19694): Loaded app: com.tencent.mobileqq
05-08 21:06:52.763 I/Xposed  (20240): Loaded app: com.tencent.mobileqq
05-08 21:06:52.776 I/Xposed  (20214): Loaded app: com.tencent.mobileqq
05-08 21:07:15.931 I/Xposed  (20543): Loaded app: com.tencent.mobileqq
05-08 21:07:17.070 I/Xposed  (20596): Loaded app: com.tencent.mobileqq
05-08 21:15:58.971 I/Xposed  (21497): WechatForwarder Loaded app: com.tencent.mm 6.3.16.49_r03ae324
05-08 21:15:58.974 I/Xposed  (21497): WechatUnrecalled: wechat version 6.3.16.49_r03ae324 not supported!
05-08 21:17:17.777 I/Xposed  (21874): Loaded app: com.tencent.mobileqq
05-08 21:19:08.507 I/Xposed  (22353): Loaded app: com.tencent.mobileqq
05-08 21:28:41.092 I/Xposed  (23201): Loaded app: com.tencent.mobileqq
05-08 21:30:41.134 I/Xposed  (25272): WechatForwarder Loaded app: com.tencent.mm 6.3.16.49_r03ae324
05-08 21:30:41.138 I/Xposed  (25272): WechatUnrecalled: wechat version 6.3.16.49_r03ae324 not supported!

**Comment by fkzhang** [comment]
请更新模块

**Comment by cxgreat2014** [comment]
05-10 23:55:21.282 I/Xposed  (14967): WechatUnrecalled (1.5.9.2) Loaded app: com.tencent.mm 6.3.16.49_r03ae324
05-10 23:55:21.402 E/Xposed  (14967): a.a.a.c.a: a.a.a.c.a: invalid CRC for file: WFHooks.apk - Wrong Password?
05-10 23:55:21.402 E/Xposed  (14967): 	at a.a.a.g.a.a(Unknown Source)
05-10 23:55:21.402 E/Xposed  (14967): 	at a.a.a.g.a.a(Unknown Source)
05-10 23:55:21.402 E/Xposed  (14967): 	at a.a.a.g.a.a(Unknown Source)
05-10 23:55:21.402 E/Xposed  (14967): 	at a.a.a.a.b.a(Unknown Source)
05-10 23:55:21.402 E/Xposed  (14967): 	at a.a.a.a.b.a(Unknown Source)
05-10 23:55:21.402 E/Xposed  (14967): 	at com.fkzhang.wechatforwarder.b.b.c(Unknown Source)
05-10 23:55:21.402 E/Xposed  (14967): 	at com.fkzhang.wechatforwarder.b.b.a(Unknown Source)
05-10 23:55:21.402 E/Xposed  (14967): 	at com.fkzhang.wechatforwarder.XposedInit.a(Unknown Source)
05-10 23:55:21.402 E/Xposed  (14967): 	at com.fkzhang.wechatforwarder.XposedInit.a(Unknown Source)
05-10 23:55:21.402 E/Xposed  (14967): 	at com.fkzhang.wechatforwarder.bu.beforeHookedMethod(Unknown Source)
05-10 23:55:21.402 E/Xposed  (14967): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:661)
05-10 23:55:21.402 E/Xposed  (14967): 	at com.tencent.mm.app.MMApplication.onCreate(<Xposed>)
05-10 23:55:21.402 E/Xposed  (14967): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1021)
05-10 23:55:21.402 E/Xposed  (14967): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4960)
05-10 23:55:21.402 E/Xposed  (14967): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
05-10 23:55:21.402 E/Xposed  (14967): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:681)
05-10 23:55:21.402 E/Xposed  (14967): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
05-10 23:55:21.402 E/Xposed  (14967): 	at android.app.ActivityThread.access$1500(ActivityThread.java:197)
05-10 23:55:21.402 E/Xposed  (14967): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
05-10 23:55:21.402 E/Xposed  (14967): 	at android.os.Handler.dispatchMessage(Handler.java:111)
05-10 23:55:21.402 E/Xposed  (14967): 	at android.os.Looper.loop(Looper.java:194)
05-10 23:55:21.402 E/Xposed  (14967): 	at android.app.ActivityThread.main(ActivityThread.java:5785)
05-10 23:55:21.402 E/Xposed  (14967): 	at java.lang.reflect.Method.invoke(Native Method)
05-10 23:55:21.402 E/Xposed  (14967): 	at java.lang.reflect.Method.invoke(Method.java:372)
05-10 23:55:21.402 E/Xposed  (14967): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1039)
05-10 23:55:21.402 E/Xposed  (14967): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:834)
05-10 23:55:21.402 E/Xposed  (14967): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
05-10 23:55:21.402 E/Xposed  (14967): Caused by: a.a.a.c.a: invalid CRC for file: WFHooks.apk - Wrong Password?
05-10 23:55:21.402 E/Xposed  (14967): 	at a.a.a.g.c.a(Unknown Source)
05-10 23:55:21.402 E/Xposed  (14967): 	at a.a.a.g.c.a(Unknown Source)
05-10 23:55:21.402 E/Xposed  (14967): 	... 27 more
05-10 23:55:21.408 E/Xposed  (14967): java.lang.ClassNotFoundException: Didn't find class "com.fkzhang.wechatforwarderhooks.Wrapper.HookWrapper" on path: DexPathList[[zip file "/data/data/com.tencent.mm/app_dex/WFHooks.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
05-10 23:55:21.408 E/Xposed  (14967): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-10 23:55:21.408 E/Xposed  (14967): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-10 23:55:21.408 E/Xposed  (14967): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
05-10 23:55:21.408 E/Xposed  (14967): 	at com.fkzhang.wechatforwarder.b.b.a(Unknown Source)
05-10 23:55:21.408 E/Xposed  (14967): 	at com.fkzhang.wechatforwarder.b.b.a(Unknown Source)
05-10 23:55:21.408 E/Xposed  (14967): 	at com.fkzhang.wechatforwarde

**Comment by cxgreat2014** [comment]
咦。。。十脸懵逼的发现重启之后莫名其妙的就正常了，thanks~
