### ISSUE TITLE
Qx插件在QQ中已不可见，Tim依旧可正常使用

### ISSUE THREAD

**Issue by Weway-git** [fkzhang/WechatUnrecalled#350]
Qx插件昨天发现在QQ设置中已不可见，
Tim依旧可正常使用
qq:7.6.0.3525
Tim:2.1.5.1754
维护开发不易，感谢大佬的付出！大佬加油！

**Comment by Moreonenight** [comment]
下载了对应版本的tim，和qq一样无法正常使用 不知道什么原因。

**Comment by Weway12306** [comment]
发现问题可能是QQ版本过低用不了的。。。。
我的QQ7.6.5升级到7.7.5就可以正常用了。。。
估计是作者升级新版插件的原因吧_(:зゝ∠)_
大佬已经在9月2号适配了7.7.5和7.7.8

**Comment by sekaiacg** [comment]
7.7.8无法使用...
mi6:miui oreo

**Comment by Weway12306** [comment]
下酷安的那个7.7.5，并升级qx再试试

**Comment by sekaiacg** [comment]
包括卸载重装qq，所有方法都试过了，无法使用
但是最新的tim2.2.8可以用，绝对是qq和谐了...

**Comment by lzh545** [comment]
说下刚试成功的办法，原先QQ版本7.2.0，插件消失后，去酷安下了多个版本（7.5.5/7.5.8/7.6.0/7.6.3/7.6.5）直接覆盖升级qq版本，重启手机测试无效。然后嫌弃7.6.5的界面，卸载了，装7.5.5后，qx又可以了。
总结：先卸qq重装试试

**Comment by Weway-git** [comment]
> Qx插件昨天发现在QQ设置中已不可见，
> Tim依旧可正常使用
> qq:7.6.0.3525
> Tim:2.1.5.1754
> 维护开发不易，感谢大佬的付出！大佬加油！
