### ISSUE TITLE
微信搜索闪退和朋友圈图片无法加载

### ISSUE THREAD

**Issue by Roeply** [fkzhang/WechatUnrecalled#374]
在更新微信7.0后会出现应用微信搜索闪退现象（模块挂起后仍存在）以及朋友圈图片加载失败（显示灰色，朋友圈视频加载正常，模块挂起后问题可恢复）

**Comment by fkzhang** [comment]
微信版本问题
http://dldir1.qq.com/weixin/android/wechat_0x27000038_1380.apk
