### ISSUE TITLE
正常使用一段时间忽然出现微信无法启动

### ISSUE THREAD

**Issue by whyou** [fkzhang/WechatUnrecalled#396]
微信版本7.0.3，wexposed版本2.2，edxposed版本0.4.1.2。正常使用几个月后，昨天忽然出现微信黑屏无反应，强制关闭微信再重新开会重复“月亮背景→黑屏”这样的循环，我测试次数不固定，5到16次，之后回到桌面。再次点击微信依然会像上面的循环。
通过禁用其他插件确认是wexposed的问题。
之后我将wexposed升级到版本2.3，情况依旧。后将微信升级为7.0.4，问题解决，但是7.0.4的dpi处理有问题，于是通过钛备份恢复到7.0.3，此时也完全正常。过了一晚上大约7个小时之后，这个问题又回来了。下面附上xposed log。

我看了log，但是开启了verbose，没看到比较详细的问题点。现在好像也没法进入wexposed去尝试清空设置之类的操作。

请问有没有好的建议？

[xposed_all_20190616_112434.log](https://github.com/fkzhang/WechatUnrecalled/files/3293805/xposed_all_20190616_112434.log)

**Comment by whyou** [comment]
edXposed有两个版本，之前用的sandHook，换用YAHFA版本之后正常了。

**Comment by edison0354** [comment]
感谢分享……我也一样的问题，换了之后好了……
