### ISSUE TITLE
微x模块显示已启用，但无法使用，微信中不显示设置

### ISSUE THREAD

**Issue by yuhangrao** [fkzhang/WechatUnrecalled#399]
Android版本：9.0
xposed：Ed xposed
系统：pixelexperience
微信版本：7.0.4
root：magisk
已安装微x模块，前段时间正常使用，突然失效了，微信中也不显示设置，在模块中显示已启用，但就是用用不了，清楚微信数据，模块数据，重置模块，重装微信和模块均无效果，依旧无法使用。
其他模块如qx等均正常
![Screenshot_20190627-120759](https://user-images.githubusercontent.com/28585220/60233800-7aaa9880-98d4-11e9-8448-759b0dc13854.png)
![Screenshot_20190627-120742](https://user-images.githubusercontent.com/28585220/60233801-7aaa9880-98d4-11e9-99fc-8eb503fb1926.png)

**Comment by System-0** [comment]
同样遇到这个问题

**Comment by StanislavskiO** [comment]
你是不是切换了账号，或者退出登录后使用了其他账号？

**Comment by DuckyQi** [comment]
并没有啊，，------------------ 原始邮件 ------------------
发件人: "StanislavskiO"<notifications@github.com>
发送时间: 2019年8月7日(星期三) 下午2:32
收件人: "fkzhang/WechatUnrecalled"<WechatUnrecalled@noreply.github.com>;
抄送: "DuckyQi"<1075105237@qq.com>;"Manual"<manual@noreply.github.com>;
主题: Re: [fkzhang/WechatUnrecalled] 微x模块显示已启用，但无法使用，微信中不显示设置 (#399)



你是不是切换了账号，或者退出登录后使用了其他账号？
 
&mdash;

**Comment by StanislavskiO** [comment]
我在激活模块之前切换了账号，安装模块后微信里什么都没有，然后我登录回原来的账号，微信里就可以使用模块了

**Comment by DuckyQi** [comment]
我下载完模块之后把微信装在框架里了，，每次启动都要有一个加载，，要有5秒左右。第一次进去之后是空白的，，登录我的号之后什么都没有，------------------ 原始邮件 ------------------
发件人: "StanislavskiO"<notifications@github.com>
发送时间: 2019年8月7日(星期三) 下午2:38
收件人: "fkzhang/WechatUnrecalled"<WechatUnrecalled@noreply.github.com>;
抄送: "DuckyQi"<1075105237@qq.com>;"Manual"<manual@noreply.github.com>;
主题: Re: [fkzhang/WechatUnrecalled] 微x模块显示已启用，但无法使用，微信中不显示设置 (#399)



我在激活模块之前切换了账号，安装模块后微信里什么都没有，然后我登录回原来的账号，微信里就可以使用模块了
 
&mdash;

**Comment by StanislavskiO** [comment]
有安装Qx的话可以去作者的网盘下载7.0.6微信和2.3wx

**Comment by MiniMiniMa** [comment]
同样遇到这个问题，下载1.x版本会显示但是实际功能不能用，而2.x版本的则直接不显示了

**Comment by led-ury** [comment]
Android版本：10.0
xposed：Ed xposed
系统：hydrogen OS
微信版本：7.0.4
root：magisk
同样遇到这个问题，微X显示启用但无法使用，同时QX显示未启用但可以使用

**Comment by hongshan666** [comment]
Android版本：10.0
xposed：lsposed
系统：MIUI12.5.3
微信版本：8.0.16
root：magisk
前段时间正常使用，有一次在设置wx模块，退出后wx设置就消失了，重装没用
