### ISSUE TITLE
请问你再我手机所有app载入模块，几个意思？

### ISSUE THREAD

**Issue by 7evenhui** [fkzhang/WechatUnrecalled#409]
![Snipaste_2019-11-18_20-28-19](https://user-images.githubusercontent.com/49709048/69052491-197d9000-0a42-11ea-958f-4a5a95eb0c39.png)
只有你的这个模块疯狂在我所有app加载，其他都是各自加载各自生效的app，你这是什么操作！？还不开源，怕是做什么见不得人的事吧？

**Comment by 7evenhui** [comment]
在这里提醒一下，在意隐私的人千万别用，这个模块加载支付宝模块十分频繁！！

**Comment by fkzhang** [comment]
xposed就是载入所有APP然后做排除 不是要挂钩的APP就跳出来
所以除了微信模块不可能挂钩其他软件 跟支付宝更没有任何关系 不想用别用 有必要在这里污蔑吗？

这是我排除微信和其他软件的代码 不信自己研究
<img width="825" alt="Screenshot 2019-11-18 at 14 01 30" src="https://user-images.githubusercontent.com/15953618/69054583-2f705e00-0a0c-11ea-8107-06caf138482e.png">

**Comment by 7evenhui** [comment]
微信包名都是固定的，为什么要用这种低效的方法？我没污蔑，只是这个不符合常规逻辑，很值得怀疑

**Comment by fkzhang** [comment]
为了兼容双开微信或其他改包名的微信

**Comment by fkzhang** [comment]
如果模块在其他软件挂钩你倒是提供证据啊

**Comment by 7evenhui** [comment]
我实在想不明白为何要用这种加载再判断包名的方法
![image](https://user-images.githubusercontent.com/49709048/69055696-5c8f3180-0a49-11ea-9549-3b3f53748725.png)

**Comment by fkzhang** [comment]
xposed就这样的 你去理解一下xposed的原理

**Comment by 7evenhui** [comment]
xposed日志里只有你这样干，其他都是各自hook各自app
你解释下上面hook 今日头条这个activity?

**Comment by fkzhang** [comment]
我解释不了 我也没有hook其他软件 也有可能是你这个捕捉异常软件弄错了 反正不信别用 很简单
