### ISSUE TITLE
微信 google play 版 7.0.12 自动电脑登陆功能不工作

### ISSUE THREAD

**Issue by zyf0330** [fkzhang/WechatUnrecalled#439]
模块版本 2.10_2.10(b9)
微信增强模块的自动登录是可以工作的，但两者一起使用，本模块会导致微信进入朋友圈时闪退

**Comment by edison0354** [comment]
羡慕Play版能用的，我就只能各种玄学黑屏闪退

**Comment by zyf0330** [comment]
@edison0354 禁用微信增强就不闪退了

**Comment by edison0354** [comment]
我甚至都没装微信增强，太玄了……

**Comment by jerrynottom0** [comment]
我也是，没有安装微信增强。清空微信安装play版7.0.12，不装微x或者不启用则不出问题。一旦装了，第二次进微信必卡死

**Comment by edison0354** [comment]
你俩sandhook还yahfa？

**Comment by zyf0330** [comment]
我 sandhook

**Comment by KylinZhangQAQ** [comment]
我的都显示适配出错，不知道啥时候能适配play版本的？还是真的就和传闻的一样play版本适配不了了么

**Comment by zyf0330** [comment]
更新到最新版，然后使用speed mode 优化。现在正常了
