### ISSUE TITLE
2.13版会自动清空收藏小程序

### ISSUE THREAD

**Issue by imkingcn** [fkzhang/WechatUnrecalled#456]
2.13版会自动清空“我的小程序”，微信用的是7.0.4(1402)play版

**Comment by imkingcn** [comment]
![Capture+_2020-01-06-23-58-16](https://user-images.githubusercontent.com/8566224/82066336-d7d45600-9701-11ea-96d5-eb0e204948b3.png)

**Comment by imkingcn** [comment]
![Capture+_2020-05-15-23-05-37](https://user-images.githubusercontent.com/8566224/82066405-f1759d80-9701-11ea-8cd9-90bf0d571365.png)

**Comment by fkzhang** [comment]
不会 跟模块无关
