### ISSUE TITLE
禁用 00327

### ISSUE THREAD

**Issue by oyange** [fkzhang/WechatUnrecalled#459]
刚装上没有使用任何功能，就显示禁用 00327。
微信版本，微x版本都改过，没有任何作用

**Comment by sambodhi-cn** [comment]
我也是这个提示，【禁用】禁用代码 00327 （微信账户名），但同一个手机，登陆另一个微信账户，就没事儿，怀疑是没有给打钱被禁用了

**Comment by fkzhang** [comment]
00327 跟模拟器有关 跟打钱无关

**Comment by sambodhi-cn** [comment]
我没用模拟器，也是这个效果，直接在root过的安卓手机上，一个账户显示被禁用，另一个账户就没事

**Comment by sambodhi-cn** [comment]
需要打钱就吱声，不要偷偷摸摸的禁止呀老大

**Comment by fkzhang** [comment]
禁用有各种原因 代码不同 00327 就是模拟器 
也有可能跟某些软件冲突 卸载冲突软件或模块就是
能打钱解决的会有打赏选项
没有就是贩卖或辱骂或其他原因被人举报的

**Comment by oyange** [comment]
@fkzhang 模拟器的问题可以解决吗？

**Comment by sambodhi-cn** [comment]
> 禁用有各种原因 代码不同 00327 就是模拟器
> 也有可能跟某些软件冲突 卸载冲突软件或模块就是
就装了这一个模块微X模块，没装别的。
> 能打钱解决的会有打赏选项
> 没有就是贩卖或辱骂或其他原因被人举报的
怎么举报的？就我自己从网盘下载的，何来贩卖或辱骂或其他原因？
