### ISSUE TITLE
WX模块显示不全异常

### ISSUE THREAD

**Issue by wxf26054** [fkzhang/WechatUnrecalled#507]
![Screenshot_2023-01-25-07-57-21-480_com tencent mm](https://user-images.githubusercontent.com/22016320/214448147-b811e4fb-53d9-4097-acf4-d89b28e2754a.jpg)
如图所示，wx模块部分界面显示不全，布局区域进入了屏幕外部。希望修复。

**Comment by fkzhang** [comment]
模块设置里搜索 宽度
