### ISSUE TITLE
微信现在支持的最高版本是多少?

### ISSUE THREAD

**Issue by wxf26054** [fkzhang/WechatUnrecalled#513]

**Comment by fkzhang** [comment]
模块设置菜单-右上角三点菜单-查看支持版本

**Comment by wxf26054** [comment]
8.0.35版本是不是不支持, 在微信设置里没有发现微x模块设置选项

**Comment by fkzhang** [comment]
只要模块正常运行不管支不支持都会显示

**Comment by wxf26054** [comment]
我用的magisk的lsposed, 之前有显示设置, 现在不显示了, Xposed也是激活的状态, 可能是因为什么问题?

**Comment by wxf26054** [comment]
找到原因了, 是因为magiskroot设置了隐藏root
